safe.directory=/storage/emulated/0/Projek Code/Meong-Univercity-Hub/Sesi-4-Meong-Univercity-(portfolio)
user.name=MeongKnight
user.email=meongknight@gmail.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/MeongKnight/MeongKnight.github.io.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
